# Generated by Django 5.0.6 on 2024-07-07 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adherents', '0003_customuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Intervenant',
            fields=[
                ('EmployeID', models.AutoField(primary_key=True, serialize=False)),
                ('Nom', models.CharField(max_length=100)),
                ('Adresse', models.CharField(max_length=255)),
                ('Telephone', models.CharField(max_length=20)),
                ('Role', models.CharField(max_length=100)),
                ('CoursID', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'intervenant',
                'verbose_name_plural': 'intervenants',
            },
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
