# Generated by Django 5.0.6 on 2024-07-07 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adherents', '0004_intervenant_delete_customuser'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='intervenant',
            options={},
        ),
        migrations.RenameField(
            model_name='intervenant',
            old_name='EmployeID',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='intervenant',
            old_name='Nom',
            new_name='nom',
        ),
        migrations.RenameField(
            model_name='intervenant',
            old_name='Role',
            new_name='role',
        ),
        migrations.RenameField(
            model_name='intervenant',
            old_name='Telephone',
            new_name='telephone',
        ),
        migrations.RemoveField(
            model_name='intervenant',
            name='Adresse',
        ),
        migrations.RemoveField(
            model_name='intervenant',
            name='CoursID',
        ),
        migrations.AddField(
            model_name='intervenant',
            name='cours_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='intervenant',
            name='email',
            field=models.EmailField(default='Unknown', max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='intervenant',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='intervenant',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='intervenant',
            name='username',
            field=models.CharField(default='Unknown', max_length=150, unique=True),
        ),
        migrations.AlterModelTable(
            name='intervenant',
            table='intervenant',
        ),
        migrations.AddField(
            model_name='intervenant',
            name='adresse',
            field=models.CharField(default='Unknown', max_length=255),
        ),
    ]
