# Generated by Django 5.0.6 on 2024-07-07 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adherents', '0005_alter_intervenant_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='intervenant',
            name='password',
            field=models.CharField(default='Unknown', max_length=128),
        ),
    ]
